version: "3.9"

services:
  loki:
    image: grafana/loki:2.9.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki-network

  promtail:
    image: grafana/promtail:2.9.0
    volumes:
      - ./promtail-config.yml:/etc/promtail/config.yml
      - "./BankSystem/logs:/app/logs/bank:ro"
      - "../PSP/PSP/psp/logs:/app/logs/psp:ro"
    command: -config.file=/etc/promtail/config.yml
    ports:
      - "9080:9080"  # Expose promtail metrics port
    depends_on:
      - loki
    networks:
      - loki-network

  grafana:
    image: grafana/grafana:10.2.2
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      - loki
    networks:
      - loki-network

networks:
  loki-network:
    driver: bridge