server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: bank-backend
    static_configs:
      - targets:
          - localhost
        labels:
          job: bank-backend
          app: bank-backend
          __path__: /app/logs/bank-backend/app.log
    pipeline_stages:
      - labels:
          level:
          logger:
## more service logs can be added here